### ISSUE TITLE
aint working ubuntu 16

### ISSUE THREAD

**Issue by mrleduck** [DeadBread76/Raid-Toolbox#1]
tested it on ubuntu 16 aint working homie
after i select choice it only shows this
![cwi0ynctrlu](https://user-images.githubusercontent.com/40295978/53497307-31704680-3aa4-11e9-8061-2e76a2724f8f.png)
and does nothing

**Comment by DeadBread76** [comment]
it doesnt support linux yet, i will do that eventually

**Comment by DeadBread76** [comment]
It supports linux now.
