### ISSUE TITLE
pip3 install discord.py NOT WORKING

### ISSUE THREAD

**Issue by 03AR69** [DeadBread76/Raid-Toolbox#101]
it says ERROR: Could not find a version that satisfies the requirement discord.js (from versions: none)
ERROR: No matching distribution found for discord.js

**Comment by Mattlau04** [comment]
wat

**Comment by lilcsz** [comment]
"No matching distribution found for discord.js" BRUH MOMENT

**Comment by Hidden-R3d** [comment]
Try using pip3 install -r requirements.txt
