### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Nacho82821** [DeadBread76/Raid-Toolbox#106]
![Screenshot_20200823-192201_Termux](https://user-images.githubusercontent.com/70079407/90984567-06ba5d80-e576-11ea-87c6-d3c791a504e7.jpg)
-_-

**Comment by xAvatar6969** [comment]
more details

**Comment by Hidden-R3d** [comment]
See https://github.com/DeadBread76/Raid-Toolbox/issues/88
