### ISSUE TITLE
Got error

### ISSUE THREAD

**Issue by Aayush2005** [DeadBread76/Raid-Toolbox#111]
Window will be a boring gray. Try adding call to change_look_and_feel('Dark Blue 3') before your layout definition
 If you seriously want this gray window and no more nagging, add  change_look_and_feel('DefaultNoMoreNagging')
Window will be a boring gray. Try adding call to change_look_and_feel('Dark Blue 3') before your layout definition
 If you seriously want this gray window and no more nagging, add  change_look_and_feel('DefaultNoMoreNagging'

**Comment by Hidden-R3d** [comment]
This isn't an issue. This is normal behavior. You can ignore this warning.

(Duplicate of https://github.com/DeadBread76/Raid-Toolbox/issues/114 )

**Comment by Mattlau04** [comment]
Not an error, just an info message
