### ISSUE TITLE
i don't know how to work with tokens

### ISSUE THREAD

**Issue by caeta1** [DeadBread76/Raid-Toolbox#115]
i've made a file with few tokens but they doesn't work when i'm trying to join servers. 
![tokens not working](https://user-images.githubusercontent.com/71738052/93949000-3778e880-fd16-11ea-95df-6b67d21a8a90.jpeg)
can somebody answer me? tnx

**Comment by Hidden-R3d** [comment]
Make sure that the tokens are valid, make sure they're formatted like this:
`token1
token2
token3
`
and make sure that they're in /rtb/tokens/example.txt or something like that.
If none of that works, make sure you're not cloudflare banned.

**Comment by Mattlau04** [comment]
Put 1 token per line, and check they aren't invalid

**Comment by caeta1** [comment]
> Make sure that the tokens are valid, make sure they're formatted like this:
> 
> token1
> token2
> token3
> 
> and make sure that they're in /rtb/tokens/example.txt or something like that.
> If none of that works, make sure you're not cloudflare banned.
I've tried doing that but it still doesn't work
![image](https://user-images.githubusercontent.com/71738052/94005670-fb28a500-fd74-11ea-9188-46709d7d08e9.png)
do you know how to fix that?

**Comment by caeta1** [comment]
yeah, i think i'm cf banned. how can i fix that?

**Comment by Mattlau04** [comment]
sire those aren't valid tokens

**Comment by caeta1** [comment]
and there is a way i can fix that?

**Comment by Hidden-R3d** [comment]
My dude. Seriously. Go online, and took up "how to get discord user tokens" or something.
