### ISSUE TITLE
Joiner, leaver, friend bomber not working

### ISSUE THREAD

**Issue by siphoned** [DeadBread76/Raid-Toolbox#116]
Joiner, Leaver Friend bomber are not working.

**Comment by Hidden-R3d** [comment]
Can you please be more detailed? Are you sure you're not cloudflare banned?

**Comment by siphoned** [comment]
> Can you please be more detailed? Are you sure you're not cloudflare banned?

Is it working for you? Because i've never used any tools like this so im not sure why i'd be cloudflare banned

**Comment by Hidden-R3d** [comment]
It works fine for me. You get cloudflare banned for a couple hours if you use the tool too much. It'll go away in about 4ish hours, or you can use a VPN to get around it.

**Comment by siphoned** [comment]
> It works fine for me. You get cloudflare banned for a couple hours if you use the tool too (especially for spamming) much. It'll go away in about 4ish hours, or you can use a VPN to get around it.

I just went to RTB > Tools> CF Checker and it said "OK" so I dont think its me being CF banned

**Comment by Hidden-R3d** [comment]
It's possible that your tokens/accounts have been disabled. Try making a new account and testing it it works with that.

**Comment by siphoned** [comment]
I have just checked with 14 tokens i have sitting around, and they are all valid. still to no avail. heres a discord invite https://discord.gg/7tRTvP

**Comment by siphoned** [comment]
> It's possible that your tokens/accounts have been disabled. Try making a new account and testing it it works with that.

Join the link above so i can talk to you easier

**Comment by Mattlau04** [comment]
Tokens were just invalid
