### ISSUE TITLE
(Wiki suggestion) Add "How to install python3 on mac" in the wiki

### ISSUE THREAD

**Issue by Hidden-R3d** [DeadBread76/Raid-Toolbox#117]
Just a thing I noticed, https://github.com/DeadBread76/Raid-Toolbox/wiki/How-to-install-Python does not include anything for mac. I'd suggest add [this tutorial on how to install python 3 on a mac](https://docs.python-guide.org/starting/install3/osx/), or just a note that there is also an installer for mac on [this page](https://www.python.org/downloads/release/python-368/). Not really an important issue, just a thing that I noticed. (Same goes for pip)

**Comment by Mattlau04** [comment]
That's because RTB has no mac support and never will
