### ISSUE TITLE
Unable to compile the whole program into one .exe with Pyinstaller 

### ISSUE THREAD

**Issue by fayeackceypa83** [DeadBread76/Raid-Toolbox#121]
Hi! For educational purposes im trying to use Pyinstaller to compile the RTB.py file into one standalone exe. However, looking through the code, it looks like RTB.py definitely depends on the RTBFiles folder/module, and ive never used PyInstaller to compile multiple .py files into one exe. 

Some problems ive faced so far for example is missing variables (that usually come from the theme.py file like menu_1 or menu_2. I tried resolving this by just moving over the theme.py code into the rtb.py file, and it kinda solved the missing variables issue.

I also tried copy/pasting attack_controller.py into rtb.py But then there was also "sys.argv[1], IndexError: list index out of range". 

Im just not very sure about how to get the program into one working .exe, along with the necessary files like config. Would really appreciate any advice on how to do this so that I can understand better about compiling large projects like this into one exe, thank you!

**Comment by Mattlau04** [comment]
why would you even want to compile it

**Comment by fayeackceypa83** [comment]
> why would you even want to compile it

for the process of learning how to compile large projects like this into an exe, im using this project as a reference so that i know how to do it when i make my own large projects in the future :)

**Comment by Mattlau04** [comment]
anyway this isn't an issue with RTB itself, so this doesn't have it's place here
