### ISSUE TITLE
FFMpeg Download Not Working

### ISSUE THREAD

**Issue by VladPutinEu** [DeadBread76/Raid-Toolbox#127]
Whenever I run the program, it always asks me to download FFMpeg, when I click "Yes" there's a window but it quickly closes, not giving me enough time to see it. This keeps on happening, over and over again.

**Comment by Hidden-R3d** [comment]
Have you tried `pip install ffmpeg` and then opening RTB again?

**Comment by VladPutinEu** [comment]
> Have you tried `pip install ffmpeg` and then opening RTB again?

Yes, the same thing is still happening.

**Comment by VladPutinEu** [comment]
@Hidden-R3d Please help.

**Comment by Hidden-R3d** [comment]
Have you tried just saying "no" when it asks?

**Comment by Hidden-R3d** [comment]
If that doesn't work, just reinstall python and/or RTB and see if it helps

**Comment by abolyderechte** [comment]
Hey
I just installed an other Version of Python and now it works. But there is still a Problem. I can’t change the status of my tokens. The attack is running for like 15 seconds and then it just turns itself off.

Also what is that Checker? I c he clef my tokens and it said they are all valid, but then I checked them with the Checker V2 and it Said they were all incorrect.

Am 11/8/20 um 06:38 schrieb Hidden-R3d <notifications@github.com>:

﻿

If that doesn't work, just reinstall python and/or RTB and see if it helps

**Comment by Hidden-R3d** [comment]
@abolyderechte Please open a new issue, don't bring up new topics on an old issue.

**Comment by VladPutinEu** [comment]
@Hidden-R3d RTB works just fine when I click no. I was just hoping that you'd be able to fix the issue.

Sorry for the late reply.

**Comment by Hidden-R3d** [comment]
@VladPutinEu Yeah, RTB is known to be buggy on that bit. ffmpeg is only used for the voice chat spammer (which doesn't work in my experience) so it's not really too important

**Comment by VladPutinEu** [comment]
@Hidden-R3d Yeah, I don't really use the voice chat spammer, so it's not really a big issue for me. I'm just hoping that someone can fix it soon because it would be a cool feature.
