### ISSUE TITLE
Could not find a version that satisfies the requirement discord.py[voice]==1.2.2

### ISSUE THREAD

**Issue by WhiteSkyAngel** [DeadBread76/Raid-Toolbox#14]
https://image.noelshack.com/fichiers/2019/27/7/1562529417-unknown.png

**Comment by xNextro** [comment]
python3 -m pip install -U discord.py[voice]==1.2.2

**Comment by xNextro** [comment]
That should fix it but first install python3

**Comment by xNextro** [comment]
If it doesnt work lmk

**Comment by WhiteSkyAngel** [comment]
Nop doesn't work

**Comment by WhiteSkyAngel** [comment]
I'm on Windows 10

**Comment by WhiteSkyAngel** [comment]
But i have a question.. The command "python3 -m pip install -U discord.py[voice]==1.2.2" doesn't work for me. Where i can put this command ? Command prompt ?

**Comment by xNextro** [comment]
first make sure you have installed python3 and if yes check if its the latest version then since ur on windows 10 try this:  py -3 -m  pip install -U discord.py[voice]==1.2.2

**Comment by NeverMine17** [comment]
@WhiteSkyAngel, Are you sure that you are using Python 3?

**Comment by WhiteSkyAngel** [comment]
I've downloaded 2 versions of python. I removed the oldest version and it's okay but i have a problem when i launch RTB file it open a cmd and when i press enter it doesn't open it anymore
