### ISSUE TITLE
Not working on termux or i dont know how to run it

### ISSUE THREAD

**Issue by emirbyte** [DeadBread76/Raid-Toolbox#140]
I tried to run the script with typing python3 RTB.py no_gui but it just says "Termux detected." How can i run it?

**Comment by emirbyte** [comment]
Oops okay no problem i fixed RTB.py these termux-toast and termux-vibrate commands are bugged so it causes tool to freeze

**Comment by RicoKage** [comment]
Would you mind helping me setup and running it?

**Comment by RicoKage** [comment]
I also can not run it on Termux for some reason and am having trouble setting it up as well

**Comment by emirbyte** [comment]
python3 RTB.py no_gui
