### ISSUE TITLE
PysimpGUI installed/not installed

### ISSUE THREAD

**Issue by JosephCordero** [DeadBread76/Raid-Toolbox#149]
Just a heads up I'm running this in Kail Linux 
I'm not exactly sure what I'm doing wrong with it. I installed the requirement.txt and at the end of the installation it said the following: 

**Installing collected packages: PySimpleGUI
  Attempting uninstall: PySimpleGUI
    Found existing installation: PySimpleGUI 4.32.1
    Uninstalling PySimpleGUI-4.32.1:
      Successfully uninstalled PySimpleGUI-4.32.1**

![image](https://user-images.githubusercontent.com/54633753/103251998-15ac8480-4949-11eb-9728-86832e784c3d.png)

**Comment by hidden-r4d** [comment]
Try running `python3 RTB.py no_tk` (or maybe its no_tk_mode ?)

If that doesn't work, you can always use the command line interface with `python3 RTB.py no_gui`

**Comment by DeadBread76** [comment]
yeah gui package is wack
