### ISSUE TITLE
You probably should remove/update the "report to deadbread" webhook.

### ISSUE THREAD

**Issue by hidden-r4d** [DeadBread76/Raid-Toolbox#159]
[The webhook used for reporting RTB errors](https://ptb.discordapp.com/api/webhooks/616161894377717761/W-2kId6tkgIaQ318b5e3wGL9pBvIE8MUVHnPdxh2eMT_ub7n3Lz_ijXhS_bhh3uU8xun) is invalid. Maybe update it or remove it?

**Comment by Mattlau04** [comment]
someone found it so we deleted it :trollface:

**Comment by hidden-r4d** [comment]
amazing

it wasnt even hidden that well, all you have to do is put it into a base64 decoder and then you get the link

**Comment by Mattlau04** [comment]
yea but gl hiding stuff in python anyways
