### ISSUE TITLE
I got cloudfare banned, what do i do? all my discord invites show as invalid...

### ISSUE THREAD

**Issue by AstroOrbis** [DeadBread76/Raid-Toolbox#160]

**Comment by hidden-r4d** [comment]
Either wait a few hours, or use a VPN.

**Comment by AstroOrbis** [comment]
What free VPN would you reccomend? I'm on MacOS btw

**Comment by hidden-r4d** [comment]
ProtonVPN is good

**Comment by AstroOrbis** [comment]
got it thx

**Comment by AstroOrbis** [comment]
Also for the "all discord invites show as invalid", it was fixed after I deleted my /discord folder... idk what file was causing the problem :p
