### ISSUE TITLE
-

### ISSUE THREAD

**Issue by cuj** [DeadBread76/Raid-Toolbox#163]
>

**Comment by cuj** [comment]
btw im using python 3.9

**Comment by hidden-r4d** [comment]
Python 3.9 is not supported.

**Comment by cuj** [comment]
@hidden-r4d I used python 3.7, but same error.

**Comment by hidden-r4d** [comment]
are you opening rtb by double clicking the rtb.py file, or are you opening it from a command prompt?

**Comment by cuj** [comment]
> are you opening rtb by double clicking the rtb.py file, or are you opening it from a command prompt?

in cmd as admin, I did `python3 rtb.py`

**Comment by hidden-r4d** [comment]
What does python3 --version return?

**Comment by ResolutePSD** [comment]
> What does python3 --version return?

I'm having the same issue as cuj. when i do the command it says I have Python 3.7.2.

**Comment by cuj** [comment]
Issue has been solved: don't install python msix package from store.rg-adguard.net (maybe also don't install from ms store) because the python msix package from store.rg-adguard might have ssl issues, instead install python from python's official website, if that's done and want to run python in cmd, don't do `python`, do the following:
`%USERPROFILE%\AppData\Local\Programs\Python\Python36\python.exe`
also don't do `pip`,
instead do `%USERPROFILE%\AppData\Local\Programs\Python\Python36\Scripts\pip.exe`.

example:

`%USERPROFILE%\AppData\Local\Programs\Python\Python36\Scripts\pip.exe install -r requirements.txt`
`%USERPROFILE%\AppData\Local\Programs\Python\Python36\python.exe rtb.py`

example for python 3.7.3 users:

`%USERPROFILE%\AppData\Local\Programs\Python\Python37\Scripts\pip.exe install -r requirements.txt`
`%USERPROFILE%\AppData\Local\Programs\Python\Python37\python.exe rtb.py`
