### ISSUE TITLE
Nice grabber 🙂

### ISSUE THREAD

**Issue by xw8-568** [DeadBread76/Raid-Toolbox#218]
Bitch ass fag

**Comment by r3ngan** [comment]
?

**Comment by xw8-568** [comment]
> > Bitch ass fag
> 
> find the token logger smartass
check line 2424 retard

**Comment by xw8-568** [comment]
> find the token logger smartass
check line 2424 retard

**Comment by xw8-568** [comment]
check line 2424 retard

**Comment by 5rq** [comment]
okay? its not used, I checked everything no where does it list h which would be the webhook

find where it was USED and I will believe you, also this repo is years old so no one cares

**Comment by 5rq** [comment]
+ webhook invaild for years also

**Comment by ssjblue-xxx** [comment]
> check line 2424 retard

checked it, decoded it, its a fucking webhook link. i swear some ppl can be really retarded as fuck

**Comment by Mattlau04** [comment]
This webhook was used for bug reports.
It's been long deleted since people kept spamming it, and is now just a relic of the past (just like this whole repo lol)
