### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by ToxicRT** [DeadBread76/Raid-Toolbox#36]
![Screenshot_7](https://user-images.githubusercontent.com/43280922/66977023-bdea6c00-f069-11e9-98c6-5801dfc41ff1.png)

**Comment by DeadBread76** [comment]
Probably running it with python2

**Comment by ToxicRT** [comment]
nop

**Comment by ToxicRT** [comment]
I reinstalled python and worked
