### ISSUE TITLE
Multiple tokens, only 2 responding

### ISSUE THREAD

**Issue by Thrallix** [DeadBread76/Raid-Toolbox#37]
Hello

I have 10 login tokens which all work according to your program.
I also managed to get them in a test server.

I have a list of socks4 proxies which also works according to your program.

Though, when i spam a channel, dms, or friendrequests, only 2 of them respond and do as I attempt.

**Comment by Mattlau04** [comment]
the other 8 are probably dead, use the checker to test

**Comment by Thrallix** [comment]
> the other 8 are probably dead, use the checker to test

I did, they are all valid.
