### ISSUE TITLE
VERY nice... you're welcome :-)

### ISSUE THREAD

**Issue by PySimpleGUI** [DeadBread76/Raid-Toolbox#38]
Saw the "Thank you" comment.  Much appreciated.  It's really cool to see someone use custom button graphics and other good GUI design work in a PySimpleGUI window.  

The screenshot in the readme is very helpful to visitors that are taking a quick look.  I think it really helps projects like this that have a GUI to offer to the user.

Congrats on your creation!

**Comment by Mattlau04** [comment]
Nicest issue here yet !
