### ISSUE TITLE
Downloading Depencies not working ?

### ISSUE THREAD

**Issue by FrenchEyes** [DeadBread76/Raid-Toolbox#39]
Hey,

so i followed everything to the letter, downloaded pip both automatically and manually (there was no actual sign whether pip was downloaded or not, just didn't give an error)

i moved on to opening RTB.py but it told me i was missing  PySimpleGUI so i did as you said and re-ran the line in cmd in RTB folder but then it tells me that pip isnt recognized even though ive ran it's download countless times...

**Comment by FrenchEyes** [comment]
fixed, just redownloaded python, made sure everything was correct. 

Note : you should update the pip download command, i was auto suggested to update it ^^
maybe make that an extra step in the wiki

**Comment by DeadBread76** [comment]
pip is a part of python, RTB has nothing to do with it
