### ISSUE TITLE
Not working in termux for android

### ISSUE THREAD

**Issue by K1LL3RZERO** [DeadBread76/Raid-Toolbox#40]
Every time I try to start up RTB on termux I would only get.

`PySimpleGUI Is not installed.
Installed PySimpleGUI Successfully.
Press Enter To Exit.`

and nothing else would appear after that. Any help fixing this issue?

**Comment by Rexogamer** [comment]
Same issue is occurring for many on iSH. Did you test it on Termux/iSH? Or did you do some edits to the run command on either?

**Comment by DeadBread76** [comment]
`python3 RTB.py no_gui`
