### ISSUE TITLE
Leaving servers doesn't work

### ISSUE THREAD

**Issue by coinstore** [DeadBread76/Raid-Toolbox#44]
Leaving server returns status code 400.
Can be fixed by simply removing <<Content-Type': 'application/json', >> in headers

**Comment by Twisted14** [comment]
Where do i find this?

**Comment by coinstore** [comment]
You have to modify "attack_controller.py".
Line 585 says "headers, proxies = setup_request(token)"
You need to overwrite the headers, so make a new line in with this content: https://pastebin.com/ZVG4dHLt (do not overwrite the existing line)
After that everything should work again

**Comment by CRO-THEHACKER** [comment]
This could be fixed with `""` to esc all esc-keys
