### ISSUE TITLE
RTB not working on Linux?

### ISSUE THREAD

**Issue by joysticks** [DeadBread76/Raid-Toolbox#46]
Hello. I'm running Manjaro Linux and I'm having an issue with RTB. I wasn't sure which requirements file to use for Linux, so I installed all of them. When installing requirements.txt, I encountered this error:  

```
ERROR: Could not find a version that satisfies the requirement PySimpleGUI==4.3.2 (from -r requirements.txt (line 10)) (from versions: 2.7.0, 2.30.0, 3.39.0, 4.0.0, 4.11.0, 4.12.0, 4.13.0, 4.13.1, 4.14.0, 4.14.1, 4.15.0, 4.15.1, 4.15.2)
ERROR: No matching distribution found for PySimpleGUI==4.3.2 (from -r requirements.txt (line 10))
```

All of the other requirements.txt files installed successfully with pip. However, when running
`python RTB.py`

It outputs, 

```
PySimpleGUI Is not installed.
Installed PySimpleGUI Successfully.
Press Enter To Exit.
```

This happens every time I run the command. I decided to run it as sudo, and now I got this:

```
PySimpleGUI Is not installed.
There was an error with installing the package PySimpleGUI, Refer to Install.log
Press Enter To Exit.
```
Here is my install.log:
`/usr/bin/python: No module named pip`

I'm not sure what to do, as PySimpleGUI is installed. Any help would be appreciated.

**Comment by Mattlau04** [comment]
maybe pip is not installed on the right version of python?

**Comment by CRO-THEHACKER** [comment]
### **PySimpleGUI is a pythonhosted pip**

for Python3 & 2 installed run: `pip3 install pysimplegui`
if just py3 run: `pip install pysimplegui`

**Comment by CRO-THEHACKER** [comment]
Ran into this prob myself too:

Run: `sudo apt-get install python3.7-tk ` to fix

**Comment by Mattlau04** [comment]
After looking into the code, it seems RTB is not detecting the OS you're using properly and has troubles installing this dependency
I'm terrible at linux so i can't really fix that, but commandlinemode skips importing PySimpleGUI, and the by CRO-THEHACKER may work, though i can't test it as i'm using windows
