### ISSUE TITLE
RTB.py Ubuntu16.4 - Sintax error

### ISSUE THREAD

**Issue by CRO-THEHACKER** [DeadBread76/Raid-Toolbox#47]
Ran the req.txt file collected all pip's and ran the RTB.py file and got the error:

`  File "RTB.py", line 1029
    lic = f"DeadBread's Raid Toolbox v{rtbversion}, Copyright (C) 2019, DeadBread\n"
                                                                                   ^
SyntaxError: invalid syntax
`

showing in python2 and python3 so i'd guess its a PyGUI sintax prob?

**Comment by CRO-THEHACKER** [comment]
Fixed last error by change too:

`lic = f("DeadBread's Raid Toolbox v{rtbversion}, Copyright (C) 2019, DeadBread\n")`

**Comment by CRO-THEHACKER** [comment]
After running that; got error:

`  File "RTB.py", line 1105
    print(f'Startup time: {t1 - t0:.2f}s')
                                        ^
SyntaxError: invalid syntax
`

**Comment by CRO-THEHACKER** [comment]
Fixed last error by:

`print(f('Startup time: {t1 - t0:.2f}s'))`

**Comment by CRO-THEHACKER** [comment]
New error:

`  File "RTB.py", line 1107
    handle.write(f'================================\nStartup time: {t1 - t0:.2f}s\n================================\n\n\n')
                                                                                                                         ^
SyntaxError: invalid syntax`

**Comment by CRO-THEHACKER** [comment]
Fixed by:

`handle.write(f('================================\nStartup time: {t1 - t0:.2f}s\n================================\n\n\n'))` 

### new error:

`  File "RTB.py", line 1412
    [sg.Text('Current Theme:',size=(13,1)),sg.Text(f"{theme_name} v{theme_version} by {theme_author}")],
                                                                                                    ^
SyntaxError: invalid syntax
`

**Comment by CRO-THEHACKER** [comment]
### Took a look at:

`layout = [
                        [sg.Text('Current Theme:',size=(13,1)),sg.Text(f"{theme_name} v{theme_version} by {theme_author}")],
                        [sg.Text('Theme Bio:',size=(13,1)),sg.Text((theme_bio))],
                        [sg.Text('Change Theme:',size=(13,1)), sg.Combo(skinlist, default_value=skin, size=(30,1)), sg.Button('Change',size=(10,1))]
                    ]`

Sintax is way off for RTB; python version is: `Python 3.5.2 (default, Oct  8 2019, 13:06:37)` Upgrading to new python3 version to see fix that fixes prob.

**Comment by CRO-THEHACKER** [comment]
##ref for uname

`uname -a` command output: `Linux [HOSTNAME] 4.4.0-173-generic #203-Ubuntu SMP Wed Jan 15 02:55:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by CRO-THEHACKER** [comment]
Upgrading system and pushing new python3 version. After that re-installing git and re-trying

**Comment by CRO-THEHACKER** [comment]
Updated; ran and got:

`PySimpleGUI Is not installed.
Installed PySimpleGUI Successfully.
Press Enter To Exit.`

**Comment by CRO-THEHACKER** [comment]
Tryed `pip3 install PySimpleGUI` didnt work

**Comment by CRO-THEHACKER** [comment]
`Requirement already satisfied: pysimplegui in /root/.local/lib/python3.7/site-packages (4.15.2)` 

Still not working!

**Comment by CRO-THEHACKER** [comment]
### FOUND FIX FOR PySimpleGUI:

`sudo apt-get install python3.7-tk `

**Comment by CRO-THEHACKER** [comment]
`Traceback (most recent call last):
  File "RTB.py", line 629, in <module>
    plugin_base = PluginBase(package='RTBFiles.plugins')
NameError: name 'PluginBase' is not defined
root@zub-HP-Notebook:/home/zknox/programming/python/downloaded-gits/Raid-Toolbox# python3.7 RTB.py
Module error: No module named 'animation'
Would you like Raid ToolBox to try and install it for you?(Y/N)y
Attempting to install requests>=2.20.1
Installed requests>=2.20.1 Successfully.
Attempting to install discord.py[voice]>=1.2.2
Installed discord.py[voice]>=1.2.2 Successfully.
Attempting to install termcolor>=1.1.0
Installed termcolor>=1.1.0 Successfully.
Attempting to install colorama>=0.4.1
Installed colorama>=0.4.1 Successfully.
Attempting to install youtube_dl>=2019.8.2
Installed youtube_dl>=2019.8.2 Successfully.
Attempting to install pyperclip>=1.7.0
Installed pyperclip>=1.7.0 Successfully.
Attempting to install animation>=0.0.6
Installed animation>=0.0.6 Successfully.
Attempting to install py-cpuinfo>=5.0.0
Installed py-cpuinfo>=5.0.0 Successfully.
Attempting to install dhooks>=1.1.0
Installed dhooks>=1.1.0 Successfully.
Attempting to install PySimpleGUI==4.3.2
There was an error with installing the package PySimpleGUI==4.3.2, Refer to Install.log
Attempting to install PySimpleGUIQt>=0.26.0
`

Still not installing- waiting fot PySimpleGUI

**Comment by CRO-THEHACKER** [comment]
The packages: psutil,  where not installed so I installed them.

psutil is a py3.7-dev repo so install: `sudo apt-get install gcc python3.7-dev`
after that you will be able to install the psutil linux pip with the command: `python3.7 -m pip install psutil`

**Comment by CRO-THEHACKER** [comment]
Found that the in-app installer was not setup right and you have to say "Y" to the installer and when it hangs up you do CONTL+C untill it goes to our next error: 

`Please Restart Raid Toolbox.

  File "RTB.py", line 1029
    lic = f"DeadBread's Raid Toolbox v{rtbversion}, Copyright (C) 2019, DeadBread\n"
                                                                                   ^
SyntaxError: invalid syntax`

##How to fix

From above we can fix that error but that puts us back to the beginning. From this I'd say the sintax needs to be updated!

**Comment by CRO-THEHACKER** [comment]
Going to move to my windows 10 box to see if this works on windows 10

**Comment by DeadBread76** [comment]
bruh what have you done to it this should literally not happen

**Comment by CRO-THEHACKER** [comment]
IDK, seems like theres an prob with the Linux push

**Comment by CRO-THEHACKER** [comment]
Im in windows rn trying to get it to install.

**Comment by CRO-THEHACKER** [comment]
`NameError: name 'PluginBase' is not defined` ???

**Comment by CRO-THEHACKER** [comment]
Got everything working in windows10 with py3.7.3
