### ISSUE TITLE
PySimpleGUI

### ISSUE THREAD

**Issue by QuickTripp** [DeadBread76/Raid-Toolbox#51]
When I try to run RTB.py, it says PySimpleGUI is not installed. Installed PySimpleGUI successfully. I go to run it again and the same error comes up. So I manually install it myself using `pip3 install PySimpleGUI`. It brings up Requirement already satisfied: PySimpleGUI in /home/QuickTripp/.local/lib/python3.7/site-packages (4.16.0). I try to run RTB.py again and the same error comes up.

**Comment by Mattlau04** [comment]
It's probably installed on the wrong version of python, do you have multiples one installed?

**Comment by Mattlau04** [comment]
From what i could see your error is the same as this one
https://github.com/DeadBread76/Raid-Toolbox/issues/46
