### ISSUE TITLE
from termux on android doesn't work

### ISSUE THREAD

**Issue by xAvatar6969** [DeadBread76/Raid-Toolbox#60]
Help me!  When I try to start RTB from Termux on android it says to me: `
PySimpleGUI Is not installed.
Installed PySimpleGUI Successfully.
Press Enter To Exit.
`

**Comment by DeadBread76** [comment]
https://github.com/DeadBread76/Raid-Toolbox/wiki/How-to-set-up-Termux-to-run-RTB
