### ISSUE TITLE
It doesn't work on Termux

### ISSUE THREAD

**Issue by xAvatar6969** [DeadBread76/Raid-Toolbox#61]
Ok.  I managed to open RTB on Termux, but it doesn't work.  I try to select an option, I enter the server ID and the channel but it doesn't work.  Help!

**Comment by xAvatar6969** [comment]
Oh, I need a token. Where I can find it?

**Comment by ElectroGamesYT** [comment]
You need to buy one

**Comment by xAvatar6969** [comment]
> You need to buy one

Uh, no I don't buy it. a free method pls?

**Comment by DeadBread76** [comment]
make some accounts lmao how else

**Comment by xAvatar6969** [comment]
> make some accounts lmao how else

ok but how do I find the tokens?

**Comment by DeadBread76** [comment]
Theres plenty of tutorials on how to find the token on youtube

**Comment by xAvatar6969** [comment]
ah ok thank you. however your tool is beautiful😊

**Comment by thsanki** [comment]
> Ok. I managed to open RTB on Termux, but it doesn't work. I try to select an option, I enter the server ID and the channel but it doesn't work. Help!

Can u tell me how u open it in termux command please
