### ISSUE TITLE
Not work on the new version of termux

### ISSUE THREAD

**Issue by lolking04** [DeadBread76/Raid-Toolbox#74]

**Comment by DeadBread76** [comment]
give more info

**Comment by lolking04** [comment]
It says pakages not installed

**Comment by lolking04** [comment]
Pysimplegui not installed and I can't install it

**Comment by lilcsz** [comment]
remove import pysimplegui on code or pip install pysimplegui

**Comment by DeadBread76** [comment]
because termux doesn't have GUI so tkinter can't be installed
the termux detection is broken so you need to specify
https://github.com/DeadBread76/Raid-Toolbox/issues/40#issuecomment-568271709

**Comment by TheWay-hue** [comment]
requests permission to install the module "requests". But after permission nothing happens.
![Screenshot_2020-06-30-22-08-12-495_com termux](https://user-images.githubusercontent.com/64380347/86168048-40478d00-bb20-11ea-9d4e-91f667ee7aab.jpg)

**Comment by xAvatar6969** [comment]
After you have installed it as the comment says before you do not have to write `python3 RTB.py`, you have to write `python3 RTB.py no_gui`

**Comment by Omar2547** [comment]
i have written that but still the same problem
