### ISSUE TITLE
all tokens invalid

### ISSUE THREAD

**Issue by Mistera91** [DeadBread76/Raid-Toolbox#76]
when i put my tokens in the tokens.txt file, all tokens are invalid, even if i create them in the official website
I can start these bots if i do a normal configuration for a normal bot but RTB says that all the tokens are invalid.
(i can't start anything like as message spammer)
Please help me

**Comment by DeadBread76** [comment]
you need user accounts not bot accounts

**Comment by Mistera91** [comment]
yeah, i see that the same time you reply, thanks
