### ISSUE TITLE
Error joining bots to server

### ISSUE THREAD

**Issue by ShinobisSneaky** [DeadBread76/Raid-Toolbox#80]
When I attempt to join bots to server link the logs output
Token NzMyMzEwNzcyNjcxMTg0OTQ2... Error: 401: Unauthorized (Code 0)
Token NzMyMzEwODYxNTkwMjk4NjU0... Error: 401: Unauthorized (Code 0)
Token NzMyMzEwNTEzMjA3NDc2Mjg1... Error: 401: Unauthorized (Code 0)
Token NzMyMzEwOTU4MTY0MTQ4NDA3... Error: 401: Unauthorized (Code 0)

**Comment by xAvatar6969** [comment]
you have to use user tokens, not bots token
