### ISSUE TITLE
Suggestion to enable even more raiding capabilities

### ISSUE THREAD

**Issue by XxLilBoPeepsxX** [DeadBread76/Raid-Toolbox#86]
Hello! Big fan of the toolkit! 

I had the thought that in a future release, a helpful feature would be the ability to make the token bots react with a specific emoji on a specific message, by indicating the emoji and the URL of the message in the server to react on. This would allow verification to be bypassed in servers that verify their members using a reaction role, and therefore allow bot's to still raid the server. I was going to make this addon myself but I thought it would be better to raise as an issue here since I know it would be helpful to more than just me :)

**Comment by Mattlau04** [comment]
Pretty sure that's already a feature, just lost in the depth of menus

Also there will probably be no more releases, the main dev left the project and i don't have the skills to make new updates myself

**Comment by XxLilBoPeepsxX** [comment]
Alright, where would you suggest that I look to find that feature? 
If your open to it I will write it as a add on and submit it as a branch to be considered... Up to you of course :)

**Comment by Mattlau04** [comment]
It's option 20 in console mode, idk about where it is in GUI mode

**Comment by XxLilBoPeepsxX** [comment]
Alright, and is it possible to add emojis to the list of emojis we can use? Or us that more complicated than adding one to the list in emojis.txt?

**Comment by DeadBread76** [comment]
you can edit the code idk i forget where it pulls emojis from

**Comment by hidden-r4d** [comment]
> you can edit the code idk i forget where it pulls emojis from

According to attack_controller.py, it takes emojis from https://canary.discordapp.com/api/v6/guilds/{server}/emojis (and there's a file with all the default emoji names in there as well, not sure if it uses that or not)
