### ISSUE TITLE
Termux loading issue

### ISSUE THREAD

**Issue by dotcom-a0n1** [DeadBread76/Raid-Toolbox#87]
hi, I tried to carry out his "python3 RTB.py no_gui" and "python3 RTB.py" immediately after I leave "Termux Detected." and the name of the session becomes (program name) + is loading ..., but besides that it doesn't give signs of life, any ideas?

**Comment by xAvatar6969** [comment]
it's very normal. try to wait 10 seconds or restart the session

**Comment by dotcom-a0n1** [comment]
> it's very normal. try to wait 10 seconds or restart the session

Yeah, however I literally waited 10 minutes and still nothing, I also tried several times to restart the session


$ cd Raid-Toolbox
$ python3 RTB.py no_gui
Option acknowledged, Saved to config.
Termux Detected.

**Comment by DeadBread76** [comment]
everything installed properly?
