### ISSUE TITLE
"PYSimpleGUI not installed... PYSimpleGUI installed successfully" every time I open the program

### ISSUE THREAD

**Issue by Hidden-R3d** [DeadBread76/Raid-Toolbox#88]
Whenever I run "python3 RTB.py" I get
`PySimpleGUI Is not installed.
Installed PySimpleGUI Successfully.
Press Enter To Exit.`

When running "pip3 install PySimpleGUI" it tells me that it's already installed.

I am using Ubuntu 18.04 LTS with python 3.6.

Any help would be greatly appreciated.

**Comment by xAvatar6969** [comment]
`python3 RTB.py no_gui`

**Comment by DeadBread76** [comment]
or install python3-tk with apt
`sudo apt install python3-tk`

**Comment by Hidden-R3d** [comment]
Thanks @xAvatar6969 , this worked perfectly.

**Comment by Hidden-R3d** [comment]
Thanks to you too, @DeadBread76 , this also worked.

**Comment by KoolSkins** [comment]
> `python3 RTB.py no_gui`
Still don't work for me
