### ISSUE TITLE
Joiner error (?)

### ISSUE THREAD

**Issue by Atharv-Agarwal** [DeadBread76/Raid-Toolbox#90]
I have checked my tokens using the token checker v1 and v2 I have 81 working tokens. But when I use the joiner it says attack running for 1 min but then does not do anything please help. I have tried using a vpn also
I am on windows

**Comment by AtomicGaming666** [comment]
hey can i get a pic of the error

**Comment by Atharv-Agarwal** [comment]
@AtomicGaming666 There is no error that I know of it says attack running but the tokens dont join the server

**Comment by AtomicGaming666** [comment]
Ok I would know how to help but when there is no error I don’t know what to look for

**Comment by Atharv-Agarwal** [comment]
Welp... @Mattlau04 Can you help?

**Comment by Mattlau04** [comment]
check that you aren't cloudflare banned

**Comment by Atharv-Agarwal** [comment]
I was then I tried with a VPN still did not work
