### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by AtomicGaming666** [DeadBread76/Raid-Toolbox#91]
i get this when trying to run it

  File "RTB.py", line 1029
    lic = f"DeadBread's Raid Toolbox v{rtbversion}, Copyright (C) 2019, DeadBread\n"
                                                                                   ^

**Comment by Mattlau04** [comment]
don't crop half the error i can't know what's the problem

**Comment by AtomicGaming666** [comment]
That’s the hole error that’s all it’s outputting

**Comment by DeadBread76** [comment]
don't run it on python2

**Comment by AtomicGaming666** [comment]
What’s python2

**Comment by AtomicGaming666** [comment]
How do I run it on python3

**Comment by AtomicGaming666** [comment]
so i install the pythons your program say to use one of them just dont install and i get this 

'python' is not recognized as an internal or external command,
operable program or batch file.

**Comment by AtomicGaming666** [comment]
ok i have uninstalled all my pythons and have reinstalled the ones this thing needs and im getting the same errors again
