### ISSUE TITLE
Libterm IOS

### ISSUE THREAD

**Issue by LustreGLT** [DeadBread76/Raid-Toolbox#93]
I tried this on libterm ios and download all the modules required but when i try to run “python RTB.py no_gui” it shows “ Lustre $ python3 RTB.py no_gui
Option acknowledged, Saved to config.
2;DeadBread's Raid ToolBox is loading...Module error: py-cpuinfo currently only works on X86 and some ARM/PPC/S390X CPUs.
Would you like Raid ToolBox to try and install it for you?(Y/N)”

**Comment by DeadBread76** [comment]
the py-cpuinfo doesnt seem to work on that cpu you can probably edit the code to remove the dependency and it might work idk
